# 这是一个springboot服务要部署在springboot中的配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmall
  labels:
    app: tmall
spec:
  # 副本数量，即启动2个服务，此处对应了2个pod
  replicas: 2
  # 模板，pod配置
  template:
    metadata:
      name: tmall
      labels:
        app: tmall
    spec:
      # pod中的容器，可以配置多个
      containers:
        - name: tmall
          # 服务镜像tag，如docker.io/xxx:1.0
          image: tmall-test:1.1
          # 镜像拉取策略，此处为本地没有才进行下载
          imagePullPolicy: IfNotPresent
          # 容器的环境变量，key-value
          env:
            - name: profile
              value: test
          # 资源配置，如cpu，内存，外部资源等
          resources:
            requests:
              memory: 200
          # 健康检查，此处直接使用springboot健康检查url
          livenessProbe:
            httpGet:
              path: /tmall/actuator
              host: localhost
              port: 8090
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
      # 重启策略，健康检查不符合预期即失活，此处配置了总是重启
      restartPolicy: Always
  selector:
    matchLabels:
      app: tmall

---
# 为了将服务暴露出去，供k8s集群外访问
apiVersion: v1
kind: Service
metadata:
  name: tmall-nodeport
spec:
  selector:
    app: tmall
  ports:
    # 直接暴露在物理机上等端口，默认范围30000-32767
    nodePort: 32700
    # 服务监听等端口，k8s内部服务间调用
    port: 8090
  type: NodePort