apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      tolerations:
        - operator: "Exists"
      nodeSelector:
        kubernetes.io/hostname: tangjizhou-ubuntu
      containers:
        - image: traefik:2.3
          name: traefik
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
          args:
            - --log.level=INFO
            - --accesslog
            - --entryPoints.web.address=:80
            - --entryPoints.websecure.address=:443
            - --entryPoints.mongo.address=:27017
            - --api=true
            - --api.dashboard=true
            - --ping=true
            - --providers.kubernetescrd
            - --serversTransport.insecureSkipVerify=true
          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: kube-system
spec:
  selector:
    app: traefik
  ports:
    - port: 80
      name: web
      nodePort: 31080
    - port: 443
      name: websecure
      nodePort: 31443
  type: NodePort




