version: '3'
services:
  nginx:
    image: nginx:latest
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 4G
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"