version: '3'
services:
  nginx:
    image: nginx:1.18.0
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4G'
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./log:/var/log/nginx"