apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: base-env
spec:
  storageClassName: jenkins
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Mi
---
# 提供的本地磁盘资源
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: base-env
  labels:
    type: local
spec:
  capacity:
    storage: 800Mi
  #该volume只能被单个节点以读写的方式映射
  accessModes:
    - ReadWriteOnce
  # 标记，将用于PersistentVolumeClaim进行绑定
  storageClassName: jenkins
  # 本地磁盘路径
  hostPath:
    path: "/Users/tangjizhou/work/dev-tool/k8s/volume/jenkins"
