apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-mq-pvc
  namespace: base-env
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi