apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: base-env
type: Opaque
data:
  root_password: "cm9vdHBhc3M="
---
# mysql服务，需要持久化数据，需要挂载磁盘
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: base-env
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.17
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            # name指定为MYSQL_ROOT_PASSWORD，可参考docker官方mysql镜像说明
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: root_password
          # 挂载在容器中的位置，为容器中的路径
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      # 本地磁盘配置，提供本地磁盘信息
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            # 名字为对应的pvc(PersistentVolumeClaim)名字
            claimName: mysql-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: base-env
spec:
  selector:
    app: mysql
  ports:
    - protocol: "TCP"
      port: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: base-env
spec:
  storageClassName: mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
# 提供的本地磁盘资源
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: base-env
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  #该volume只能被单个节点以读写的方式映射
  accessModes:
    - ReadWriteOnce
  # 标记，将用于PersistentVolumeClaim进行绑定
  storageClassName: mysql
  # 本地磁盘路径
  hostPath:
    path: "/Users/tangjizhou/work/dev-tool/k8s/volume/mysql"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mysql
  namespace: base-env
spec:
  entryPoints:
    - mysql
  routes:
    - match: HostSNI(`*`)
      kind: Rule
      services:
        - name: mysql
          port: 3306