apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: base-env
spec:
  storageClassName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
# 提供的本地磁盘资源
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: base-env
  labels:
    type: local
spec:
  capacity:
    storage: 200Mi
  #该volume只能被单个节点以读写的方式映射
  accessModes:
    - ReadWriteOnce
  # 标记，将用于PersistentVolumeClaim进行绑定
  storageClassName: redis
  # 本地磁盘路径
  hostPath:
    path: "/Users/tangjizhou/work/dev-tool/k8s/volume/redis"
